Update Localizable.strings
nextcloud/ios pull request #1594
Opened 2021-05-06 15:36 UTC by castillo92

The first two options are related, the thrid is completely different. I think the spelling is better.

Signed-off-by: castillo92 <javiercizquierdo@gmail.com>

2021-05-07 09:39 UTC, Valdnet commented
The current sentence syntax is a bit confusing to the user as it tells you to select an image or take a picture and then it tells you not to select anything.

2021-05-07 10:10 UTC, rakekniven commented
Idea:
"Select an image or take a picture and use it as background. You can also select nothing. Press 'Done' to complete."

2021-05-07 10:11 UTC, rakekniven commented
@castillo92 You need to branch from "develop", not "master".

2021-05-07 12:37 UTC, rakekniven requested changes
See comment.

2021-05-10 06:54 UTC, castillo92 commented
> 
> 
> @castillo92 You need to branch from "develop", not "master".

So, I should close this PR and create a new one?

I did not know it, sorry.

2021-05-10 07:08 UTC, Valdnet commented
> So, I should close this PR and create a new one?

Yes. Close this PR and create a new branch "develop" with a rakekniven suggestion 😉.

2021-05-10 07:40 UTC, closed without merging

2021-05-10 08:42 UTC, castillo92 commented
Closed this PR and created a new PR in the right branch and with a best string:

2021-05-10 09:23 UTC, Valdnet commented
@castillo92 See my comment in the new PR 😉.

2021-05-11 10:28 UTC, rakekniven commented
There is a function called "rebase" in git. This helps to switch branches.

2021-05-11 12:51 UTC, castillo92 commented
> There is a function called "rebase" in git. This helps to switch branches.

I learn a lot with you! =)