rotate_image_pull_request
nextcloud/ios pull request #1734
Opened 2021-11-02 10:29 UTC by tsdimobile

- we created a new file preview action menu entry called "Rotate right" (below menu entry "Details") with rotate icon (see attached zip)
- we implemented rotate function:
- after taping on rotate menu element, the image rotates 90 degrees clockwise
- Image is resized to fill the viewport in either width or height (whichever is reached first)
- we saved the rotated image to the server

![Simulator Screen Shot - iPhone 12 - 2021-11-01 at 13 05 `23](https://user-images.githubusercontent.com/87704774/139829890-12fe487a-1436-471a-a652-f1f7b4a0313f.png)`

2021-11-04 07:09 UTC, tobiasKaminsky commented
Is this shown also in file list?
Or only when user actually is in photo preview and then clicks "..."? <- I prefer this, as it does not clutter the option menu.

2021-11-04 07:45 UTC, tsdimobile commented
@tobiasKaminsky rotate image option is added only when user clicks on 3 .dot menu when previews the image, we haven't added this in option Menu.

2021-11-04 10:41 UTC, thisIsTheFoxe requested changes
Hi, and thank you for your contribution, what a nice idea.
Looks good so far.

Is there a reason why this can't be added to `NCViewerQuickLook` instead? Like a simple navigation item next to the markup one? Another advantage would be that you could rotate multiple times, without saving and uploading every single time, just when you're *done*.
Also, I noticed that after rotating the image doesn't update, it just vanishes. Would be great to have a better UX. If nothing else, at least make sure the detail view pops back.

Thanks again :)

2021-12-20 11:37 UTC, harshaltsystems commented on iOSClient/ScanDocument/ScanCollectionView.swift
> +        if self.size.height == 0.0 || self.size.width == 0.0 {
Fixed

2021-12-20 11:37 UTC, harshaltsystems commented on iOSClient/Viewer/NCViewerMedia/NCViewerMediaZoom.swift
> +        if rotatedImage == nil {
Fixed

2021-12-20 11:41 UTC, harshaltsystems commented
Rotate image functionality changed 
- Confirmation dialogue added before leaving the rotated imaged screen.
- If user confirms the changes then request for rotate image proceeds.

2021-12-21 09:12 UTC, thisIsTheFoxe commented
Hi @harshaltsystems,
Thanks a lot for all your work and for keeping this PR active!
Please note that Nextcloud enforced the [Developer Certificate of Origin (DCO)](https://github.com/thisIsTheFoxe/ios#creating-pull-requests) on pull requests. Make sure that you know what that means and confirm it by signing off all your commits. E.g. like this:
```
git rebase HEAD~6 --signoff
git push --force-with-lease origin pr_rotate_image
```
<br/>

> Is there a reason why this can't be added to NCViewerQuickLook instead? Like a simple navigation item next to the markup one? Another advantage would be that you could rotate multiple times, without saving and uploading every single time, just when you're done.

Also, feel free to let me know what you think about this approach..? I think this would have a much more intuitive UX and avoids cluttering up the menus..

2023-01-16 09:25 UTC, closed without merging