Fix/conflict
nextcloud/ios pull request #1747
Opened 2021-11-10 10:03 UTC by marinofaggiana

Fix keep both conflict action

2021-11-10 14:06 UTC, thisIsTheFoxe submitted a review, later dismissed
Thanks, looks good already.
However, the problem is that all the files are not moved (only *MOV*s?). I'm still getting an error...

2021-11-10 14:06 UTC, thisIsTheFoxe commented on iOSClient/Main/Create cloud/NCCreateFormUploadConflict.swift
>              if metadatasConflictNewFiles.contains(metadata.ocId) && metadatasConflictAlreadyExistingFiles.contains(metadata.ocId) {
I'm not sure about the difference between `metadatasConflictNewFiles` and `metadatasConflictAlreadyExistingFiles`. Would you mind to explain what they are used for? Or better, add documentation for those.

2021-11-10 14:29 UTC, marinofaggiana commented on iOSClient/Main/Create cloud/NCCreateFormUploadConflict.swift
> +            self.buttonContinueTouch(self)
feel free to edit

2021-11-10 14:30 UTC, marinofaggiana commented on iOSClient/Main/Create cloud/NCCreateFormUploadConflict.swift
> +            for metadata in self.metadatasUploadInConflict {
hahaha no

2021-11-11 08:03 UTC, marinofaggiana commented
@thisIsTheFoxe approve this

2021-11-11 08:06 UTC, thisIsTheFoxe commented
Hi @marinofaggiana thanks for pinging me, I'll get to this as soon as I can.
But please note the comment of my last review. I can't see all the files being moved. I'm pretty sure that's still the case which would mean the original issue still persists.

2021-11-11 10:53 UTC, thisIsTheFoxe requested changes
Yes, as I thought.. the error is still there.
Please make sure the "keep both" option is working. For details see also #1742 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-11-11 at 11 51 50](https://user-images.githubusercontent.com/18512366/141285799-42415949-a44a-4d41-8b26-bf558575079c.png)

2021-11-11 11:18 UTC, marinofaggiana commented
I have tested and works ... "keep both", are you sure of you use this PR ?

2021-11-11 11:38 UTC, thisIsTheFoxe commented
Yes, but the issue is about *files* not media. E.g. a .PDF or .TXT file.

2021-11-11 11:50 UTC, marinofaggiana commented
Ah. ok I think it's another source ...

2021-11-11 14:37 UTC, thisIsTheFoxe approved these changes

2021-11-11 14:37 UTC, merged