sharing 3 pr new files added
nextcloud/ios pull request #1836
Opened 2021-12-27 12:12 UTC by tsdimobile

2022-01-03 11:13 UTC, thisIsTheFoxe commented
Hi @tsdimobile,
Thanks a lot for this nice PR! I really like the idea... and think it's a lot better idea than just using NCMenu for everything as I tried initially in #1799
There are still quite a few issues, but I think the first and foremost is to fix the conflicts and apply all the changes to the correct `develop` branch while being careful not to to undo any changes or bug fixes (like having activities and comments in one view).

<hr/>

Few top-level things I noticed / to consider:
- It's not possible to create more than one share link. Either:
  - Add "create new" option to the share menu
  - Always keep a static "add new share link" cell on top of all 
  - or another, better option I didn't think of..?
- This increases UX complexity / interaction cost
  - increases the number of taps by 2 (tapping on the menu to get to the detail view & tapping to apply changes)
    - And yes, number of taps is not everything and clarity is definitely more important. But I think it might be easier to just let the user tap the cell or the "..." menu and navigate directly to the detail without showing a menu before. I don't think there's a big advantage in having it. Obviously the actions would then be part of the detail view. Also also, I'm not sure if things like the link title and "Hide download" would categories as "Advanced permissions"
  - Toggle / switches should show immediate results and it would change the current behaviour (save immediately). I'm a bit unsure about this, since I can also see how an unstable internet connection can make a "apply changes" button very reasonable....

2022-01-10 13:02 UTC, tsdimobile commented
Hi @thisIsTheFoxe 
Conflicts are resolved

2022-01-10 13:59 UTC, thisIsTheFoxe commented
@tsdimobile Perfect, thank you.
Next, please make sure that your branch still builds and works as expected (check the `NCShare.storyboard` for your _'NCShareAdvancePermission'_ identifier). Also note, that we recently added [SwiftLint](https://github.com/realm/SwiftLint) to this project to improve readability and overall code quality. If possible, please ensure that especially new files are in compliance with our SwiftLint rules. 

Also, keep in mind my last comment about the fact that there is currently no way of creating multiple share links, is there?  I think the easiest solution would be to include it in the `NCMenu` that also includes the "Unshare" action. But feel free to   let me know if you have another idea..

2022-01-12 10:40 UTC, tsdimobile commented
Hi @thisIsTheFoxe 
We have fixed NCShare storyboard issue and now you can create multiple share links and unshare also

2022-01-12 14:57 UTC, thisIsTheFoxe commented
Thanks for your effort. 
As you can see, the CI fails. Please make sure:
- not to change the location or project settings concerning the `GoogleService-Info.plist`
- to fix as many linting issues as possible, especially linting errors
- to signoff every commit, for the [DCO](https://github.com/nextcloud/ios#dco-signoff)

2022-01-14 07:57 UTC, tsdimobile commented
Hi @thisIsTheFoxe ,
We have fixed the swiftlint errors, now you can build the application.

2022-01-17 14:28 UTC, thisIsTheFoxe requested changes
Thanks for your work.
Please note that the CI build still fails.
Also note that there are a few minor lint issues that haven't been fixed yet.

As you probably can see, this is a rather large PR so it may take some time to get everything right. Nevertheless, thanks a lot for contributing! <3

2022-03-23 04:41 UTC, tsdimobile commented on iOSClient/Share/NCShare.swift
> +            networking?.createShareLink(password: "")
We did not ask for password while creating the link

2022-03-30 09:13 UTC, tsdimobile commented
Hi @thisIsTheFoxe ,
I have did all the changes mentioned above and pushed the code.
Can you please review it and let me know if there anything required.

2022-04-05 16:28 UTC, thisIsTheFoxe commented
Hi @tsdimobile,
Thanks a lot for your effort on this!
However, since there was no activity in Jan-Mar we decided to implement the ideas ourselves using some parts of your code as well. I suggest that in order to speed up the development of this feature #1931 should _replace_ this PR. Feel free to check it out and let us know what you think.
We'll keep this PR open for now until we reached a final decision.

2022-05-04 12:09 UTC, thisIsTheFoxe commented
Closing this in favour of #1931

2022-05-04 12:09 UTC, closed without merging