Improved PDF Viewer
nextcloud/ios pull request #1981
Opened 2022-04-29 10:36 UTC by marinofaggiana

Issue: A page that is not next in numbering has opened, the thumbnails overlap each other.
Result: Use the vertical preview with scrollview (always open on iPad, with edge swift gesture in iPhone)

https://github.com/nextcloud/ios/issues/1944

2022-05-02 14:21 UTC, thisIsTheFoxe requested changes
Looks pretty good. I like the new thumbnails view and the swipe gesture. 👍
Please just have another look at the page view and the tip message. 
Other than that it's just details..

2022-05-02 14:21 UTC, thisIsTheFoxe commented on iOSClient/Viewer/NCViewerPDF/NCViewerPDF.swift
> +    private let appDelegate = UIApplication.shared.delegate as! AppDelegate
`appDelegate` is not used / needed in this VC.

2022-05-02 14:21 UTC, thisIsTheFoxe commented on iOSClient/Viewer/NCViewerPDF/NCViewerPDF.swift
> +        handlePageChange()
That's a pretty long function. Would be good if that could be refactored and split up a bit into smaller parts. That's also the only lint error (except for 1 force_case). So, if you decide to work on that feel free to remove the file from the `.swiftlint.yml` list.

2022-05-02 17:09 UTC, marinofaggiana commented on iOSClient/Viewer/NCViewerPDF/NCViewerPDF.swift
> +import SwiftUI
mmmm I don't know!!

2022-05-03 08:43 UTC, thisIsTheFoxe reviewed
Thanks for fixing it. I like the bigger corner radius. 👍

One more thing I noticed is that it doesn't work very well while zoomed in. Not sure if there's a better solution to this wdyt?

https://user-images.githubusercontent.com/18512366/166425716-5e726128-34f8-44be-a9ef-c32b2012f993.mov


EDIT: Also, I think you can remove the `pdf-horizontal` `pdf-vertical` icon images from the assist.

2022-05-03 08:46 UTC, marinofaggiana commented
> Thanks for fixing it. I like the bigger corner radius. 👍
> 
> One more thing I noticed is that it doesn't work very well while zoomed in. Not sure if there's a better solution to this wdyt?
> 
>  Screen.Recording.2022-05-03.at.10.39.12.mov

Yes ... exists a solution ... (intercept the event on delegate ... see what I can do) ...

2022-05-04 12:30 UTC, marinofaggiana commented
@thisIsTheFoxe can you approve this PR (after I create another for the last issue ) ?

2022-05-04 12:35 UTC, thisIsTheFoxe approved these changes
👍

2022-05-04 12:46 UTC, merged