Fix user agent for text app
nextcloud/ios pull request #1985
Opened 2022-05-03 12:54 UTC by thisIsTheFoxe

Fix #1967 

- allow pasting images from the pasteboard + preview (NC 24)
- fix keyboard dismisses after *Cut*
- potential fix for:
  - #1631 
  - nextcloud/text#1927

2022-05-04 10:16 UTC, marinofaggiana commented on iOSClient/Utility/NCUtility.swift
> +import WebKit
Need WebKit ?

2022-05-04 10:16 UTC, marinofaggiana requested changes
Read comments.

2022-05-04 10:28 UTC, thisIsTheFoxe commented on iOSClient/Utility/NCUtility.swift
> +import WebKit
Used for testing. Removed it.

2022-05-05 08:33 UTC, marinofaggiana approved these changes

2022-05-05 08:34 UTC, merged