Add new section in settings for Nextcloud apps
nextcloud/ios pull request #2461
Opened 2023-06-12 14:40 UTC by mpivchev

This adds a new section in settings to promote our other apps.

2023-06-15 11:08 UTC, mpivchev commented on iOSClient/More/NCMore.swift
> -    @IBOutlet weak var displayName: UILabel!
These were separated in their own files

2023-06-15 11:09 UTC, mpivchev commented on iOSClient/More/Cells/BaseNCMoreCell.swift
> +    }
This code was used for every cell, so I made a base class instead.

2023-06-16 07:45 UTC, tobiasKaminsky commented
Can you use 
[![image](https://github.com/nextcloud/ios/assets/5836855/008cdcd0-4ac9-4895-bc4e-5c8cde2f1b8b)](https://github.com/nextcloud/desktop/blob/d8479fb1bafacbef2ecdb26516b9c7f513204f01/theme/white/more-apps.svg?plain=1)

for more icon?

2023-06-16 13:25 UTC, mpivchev commented
> we could take the opportunity to migrate this simple view into swiftUI and the GUI does not convince me

Hmm, we could've decided to do this earlier before these changes were made. But I can try nonetheless.

> the GUI does not convince me

Any suggestions are welcome. We can maybe ask some of our UI designers to design a view.

2023-06-21 16:16 UTC, jancborchardt requested changes
Nice! Design-wise, how about something standard like Apple also uses on the top of Contacts? That has proper spacing and all.
![](https://help.apple.com/assets/640A52196275DE31D4371B5E/640A52226275DE31D4371B8B/en_US/e051d0317543b275c899f9afa1780c25.png)

2023-06-21 16:20 UTC, mpivchev commented
@jancborchardt you mean this part?

<img width="439" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/2c828ccb-5501-4560-a462-cfacb9bc4f57">

Since we only have 3 of these, should they be stacked left or be in the middle?

2023-06-22 05:12 UTC, marcoambrosini reviewed
I don't think that these shortcuts should be the first entry in the settings because they can be detrimental to usability and create friction. I would say that settings is probably the wrong place to advertise the presence of other apps, and I suggest something subtler and "dismissable". if we absolutely have to, what about moving them to the bottom of the list?
Also, would these be visible even for users that have these apps installed?

2023-06-22 08:02 UTC, mpivchev commented
> I don't think that these shortcuts should be the first entry in the settings because they can be detrimental to usability and create friction. I would say that settings is probably the wrong place to advertise the presence of other apps, and I suggest something subtler and "dismissable". if we absolutely have to, what about moving them to the bottom of the list?

I see your point. I still need to move this forward however, so if @jancborchardt is ok with this I can move this section to the bottom.

2023-06-22 09:08 UTC, jancborchardt commented
> Since we only have 3 of these, should they be stacked left or be centered?

@mpivchev is there any recommended default or standard? Centered seems good.

---

@marcoambrosini the issue if they are on the bottom is that they will be difficult to discover, defeating the purpose. It is obvious that the vertical list of entries goes on, but it would not be obvious that there is an entirely new element below.

2023-06-22 09:47 UTC, mpivchev commented
@jancborchardt Here is the updated look:
![image](https://github.com/nextcloud/ios/assets/6960329/c81db9ba-9681-41d8-a190-0a38cf6f5c53)

2023-06-22 10:16 UTC, mpivchev commented
@jancborchardt Here is the new look:

<img src="https://github.com/nextcloud/ios/assets/6960329/ee095c1f-1a82-4ad9-aa83-f2409305eb0c" width="300" height="650">

<img src="https://github.com/nextcloud/ios/assets/6960329/e644ad70-8e8e-46e7-91eb-f450933b081f" width="300" height="650">

2023-06-22 10:30 UTC, jancborchardt commented
In iOS Contacts, there is a bit more top and bottom padding inside the entries. Can you adjust that @mpivchev? :)

2023-06-22 14:10 UTC, mpivchev commented
@jancborchardt Is this better?
<img src="https://github.com/nextcloud/ios/assets/6960329/83b85ed5-3884-4aba-8c7f-8668dd724733" width="300" height="650">

2023-06-23 16:11 UTC, mpivchev commented
@jancborchardt pinging again in case you missed it

2023-06-26 09:26 UTC, jancborchardt approved these changes
Latest screenshot looks good! :)

2023-06-26 10:22 UTC, merged

2023-06-30 15:51 UTC, hannesfritz commented
iOS seems to stretch those buttons if less are available. I just found an example with 4 instead of 5 like in the screenshot above. But I did an additional mockup to show what it might look with only the three options. 
In my opinion it is calmer on the eye, better aligned and additionally larger tap targets.

So just food for thought :) 
![Contacts 4 jumps](https://github.com/nextcloud/ios/assets/1778260/ffead7ce-e16c-4f3c-b5d5-67a7c08c7d57)
![Nextcloud more](https://github.com/nextcloud/ios/assets/1778260/4754d99b-9cfe-4a59-a3d0-25625e393ad1)

2023-06-30 16:05 UTC, jancborchardt commented
Yeah, that seems very nice @hannesfritz!

@mpivchev could you adjust them like that? :)

2023-07-05 12:20 UTC, mpivchev commented
Branch restored so I can reimplement this soon